server:
  port: 8000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: soothsayer-db-dev
  redis:
    host: localhost
    port: 6379
  application:
    name: soothsayer-authn
security:
  basic:
    enabled: false
  oauth2:
    authorization:
      realm: soothsayer/iam
    resource:
      id: soothsayer-api
      filter-order: 3
logging:
  level.org.springframework.security: DEBUG



